version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    driver: bridge

volumes:
  customer-db-storage:
  activemq-storage:
  redis-inmemory-storage:
#  mongo-db-storage:

services:
  customer-db:
    image: mysql:8.0.13
    environment:
      MYSQL_DATABASE: customerDB
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - 3306:3306
    networks:
      - web-app-net
    volumes:
      - customer-db-storage:/var/lib/mysql

  phpadmin-auth:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: customer-db
      PMA_PORT: 3306
      PMA_PMADB: customerDB
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - 8092:80
    networks:
      - web-app-net
    depends_on:
      - customer-db
    restart: on-failure

  activemq:
    image: webcenter/activemq
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    restart: on-failure
    networks:
      - web-app-net
    volumes:
      - activemq-storage:/var/log/activemq

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - web-app-net
    volumes:
      - redis-inmemory-storage:/data

#  mongo-db:
#    image: mongo:latest
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: testDB
#    restart: on-failure
#    networks:
#      - web-app-net
#    volumes:
#      - mongo-db-storage:/data/db

#  mongo-express:
#    image: mongo-express:latest
#    ports:
#      - 8091:8081
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo-db
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
#      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_BASICAUTH_USERNAME: dev
#      ME_CONFIG_BASICAUTH_PASSWORD: devP@ss
#    restart: on-failure
#    depends_on:
#      - mongo-db
#    networks:
#      - web-app-net

#end of scripts