version: '3.5'

networks:
   web-app-net:
       name: my-web-app-net
       driver: bridge

services:
   customer-service-ui:
       image: customer-service-ui:1.0
       build:
          context: ./CustomerServiceUI
          dockerfile: Dockerfile
       environment:
          app.db.name: customerDB
          app.db.host: customer-db
          app.db.port: 3306
          app.db.password: root@123
          app.db.mysql.url.query: ?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
          app.customer.host: localhost
          app.customer.port: 8080
          app.customer.api: /api/customer/v1/profile
       ports:
          - 80:8080
       restart: on-failure
       networks:
          - web-app-net